<script src="/admin/js/core/jquery.min.js"></script>
<script src="/admin/js/core/popper.min.js"></script>
<script src="/admin/js/core/bootstrap.min.js"></script>
<script src="/admin/js/plugins/perfect-scrollbar.jquery.min.js"></script>
<script src="/admin/js/plugins/moment.min.js"></script>
<script src="/admin/js/plugins/locale_moment_pt-br.js"></script>
<script src="/admin/js/plugins/bootstrap-switch.js"></script>
<script src="/admin/js/plugins/sweetalert2.min.js"></script>
<script src="/admin/js/plugins/jquery.validate.min.js"></script>
<script src="/admin/js/plugins/jquery.bootstrap-wizard.js"></script>
<script src="/admin/js/plugins/bootstrap-selectpicker.js"></script>
<script src="/admin/js/plugins/bootstrap-datetimepicker.js"></script>
<script src="/admin/js/plugins/jquery.dataTables.min.js"></script>
<script src="/admin/js/plugins/bootstrap-tagsinput.js"></script>
<script src="/admin/js/plugins/jasny-bootstrap.min.js"></script>
<script src="/admin/js/plugins/fullcalendar.min.js"></script>
<script src="/admin/js/plugins/jquery-jvectormap.js"></script>
<script src="/admin/node_modules/trumbowyg/dist/trumbowyg.min.js"></script>
<script src="/admin/js/plugins/nouislider.min.js"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
<script src="/admin/js/plugins/chartjs.min.js"></script>
<script src="/admin/js/plugins/bootstrap-notify.js"></script>
<script src="/admin/js/now-ui-dashboard.min.js?v=1.1.0" type="text/javascript"></script>
<script src="/cdn/demo/demo.js"></script>
<script src="/admin/js/main.js"></script>
